### ISSUE TITLE
problems to continue the installation of jdownloader script

### ISSUE THREAD

**Issue by Diegoloex** [StevenSeifried/proxmox-scripts#12]
Hello, sorry to bother you with a question, probably absurd.

I have installed jdownloader with your script, thank you very much for your work, it is great.
The question: how do I continue? I have only got the active machine and an ip. I don't know how to continue and be able to see the graphical interface.

Really, thank you very much for the time spent doing these things, and sorry for my poor knowledge of these systems. a huge greeting

**Comment by StevenSeifried** [comment]
Gladly I help you further

1. Create an account on [my.jdownloader.org](https://my.jdownloader.org/)
2. Run `sudo -u jdown2 java -jar /opt/jdown2/JDownloader.jar -norestart` in the  LXC console. jdown2 will do some magic stuff. After jdown2 is finished with that (may you have to re-run the command), you will see this 
![grafik](https://user-images.githubusercontent.com/39765956/208235316-3d00acf5-219a-478f-a5ab-2b516e56c496.png)
Press `Y` and enter your credentials of my.jdownloader.org
3.  jdown2 will do some magic stuff again. 
4. Now you should see your new jdownloader on my.jdownloader.org \
![grafik](https://user-images.githubusercontent.com/39765956/208235494-e8304f4e-9440-4a02-9869-a7c0f7f9bc74.png)
5. Click onto it to start, but i recommend switching back to the container, pressing `Ctrl + C` and the rebooting the container with the command `reboot`
6. jdown2 will autostart at every boot of the container

**Comment by Diegoloex** [comment]
***@***.***:~# sudo -u jdown2 java -jar /opt/jdown2/JDownloader.jar -norestart 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.appwork.utils.ReflectionUtils (file:/opt/jdown2/JDownloader.jar) to field java.io.PrintStream.charOut
WARNING: Please consider reporting this to the maintainers of org.appwork.utils.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO >> [sun.Desktop: null, XDG_CURRENT_DESKTOP: null, XDG_SESSION_TYPE: null, KDE_FULL_SESSION: null, KDE_SESSION_VERSION: null, DESKTOP_SESSION: null, GNOME_DESKTOP_SESSION_ID: null]
Simple boolean - boolean
Simple class java.lang.Boolean - Boolean
Simple class java.lang.String - String
Simple double - double
Simple class java.lang.Number - Number
Simple class java.lang.Double - Double
Simple int - int
Simple class java.lang.Integer - Integer
Simple float - float
Simple class java.lang.Float - Float
Simple long - long
Simple class java.lang.Long - Long
Simple byte - byte
Simple class java.lang.Byte - Byte
Simple short - short
Simple class java.lang.Short - Short
Simple char - char
Simple class java.lang.Character - Character
Simple class java.lang.Object - Object
Simple class java.util.Date - Date
INFO >> Prefer (merged) JSon Storage from File: /opt/jdown2/cfg/org.appwork.utils.logging2.LogConfig.json

THREAD: 1
1|Log.L.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Application Root: /opt/jdown2
SystemEntropyWorkaround:false
Multiple LogControllers Detected: org.appwork.utils.logging2.extmanager.LoggerFactory|Mode:NORMAL
Multiple LogControllers Detected: ***@***.***
1|Log.L.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /opt/jdown2/cfg/org.jdownloader.update.lastchance.LastChanceConfig.json

THREAD: 1
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: awt.toolkit: sun.awt.X11.XToolkit
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.specification.version: 11
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: sun.cpu.isalist: 
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: classloader_00000001: org.jdownloader.update.launcher.CL2
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: sun.jnu.encoding: ANSI_X3.4-1968
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: classloader_00000000: org.jdownloader.update.launcher.ClassLoaderExtensionImpl
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: extlogmanager.avoidsystemclassloader.hack: ***@***.***
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.class.path: /opt/jdown2/JDownloader.jar
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vm.vendor: Debian
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: sun.arch.data.model: 64
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.util.Arrays.useLegacyMergeSort: true
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vendor.url: https://tracker.debian.org/openjdk-11
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: user.timezone: Europe/Madrid
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: os.name: Linux
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vm.specification.version: 11
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: sun.java.launcher: SUN_STANDARD
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: user.country: US
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.net.preferIPv6Addresses: system
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: sun.boot.library.path: /usr/lib/jvm/java-11-openjdk-amd64/lib
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: sun.java.command: /opt/jdown2/JDownloader.jar -norestart
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.rmi.server.useCodebaseOnly: true
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: jdk.debug: release
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: sun.cpu.endian: little
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: user.home: /home/jdown2
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: user.language: en
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: LOG_INIT_DONE: 2 instances
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.specification.vendor: Oracle Corporation
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.version.date: 2022-07-19
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.home: /usr/lib/jvm/java-11-openjdk-amd64
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: file.separator: /
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vm.compressedOopsMode: 32-bit
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: line.separator: 

1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.specification.name: Java Platform API Specification
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vm.specification.vendor: Oracle Corporation
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: org.appwork.LoggerFactory: org.appwork.utils.logging2.LogSourceRedirector
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: sun.management.compiler: HotSpot 64-Bit Tiered Compilers
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: com.sun.jndi.rmi.object.trustURLCodebase: false
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.runtime.version: 11.0.16+8-post-Debian-1deb11u1
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: user.name: jdown2
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: path.separator: :
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: com.sun.jndi.cosnaming.object.trustURLCodebase: false
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: os.version: 5.15.64-1-pve
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.runtime.name: OpenJDK Runtime Environment
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: file.encoding: ANSI_X3.4-1968
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vm.name: OpenJDK 64-Bit Server VM
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vendor.url.bug: https://bugs.debian.org/openjdk-11
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.io.tmpdir: /tmp
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.version: 11.0.16
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: user.dir: /tmp/hsperfdata_jdown2
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: os.arch: amd64
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vm.specification.name: Java Virtual Machine Specification
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.awt.printerjob: sun.print.PSPrinterJob
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: k: 0dd0ecf7f742873d745106adea00b64a
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: sun.os.patch.level: unknown
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.util.logging.manager: org.appwork.utils.logging2.extmanager.ExtLogManager
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vm.info: mixed mode, sharing
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vendor: Debian
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.vm.version: 11.0.16+8-post-Debian-1deb11u1
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: com.sun.jndi.ldap.object.trustURLCodebase: false
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: sun.io.unicode.encoding: UnicodeLittle
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysProp: java.class.version: 55.0
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: SUDO_USER: root
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: SUDO_COMMAND: /usr/bin/java -jar /opt/jdown2/JDownloader.jar -norestart
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: SUDO_GID: 0
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: SHELL: /sbin/nologin
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: MAIL: /var/mail/jdown2
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: LOGNAME: jdown2
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: TERM: linux
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: SUDO_UID: 0
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: USER: jdown2
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: LANG: C
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> SysEnv: HOME: /home/jdown2
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> jar:file:/opt/jdown2/JDownloader.jar!/version.nfo:
${updateclient.revision}
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.utils.Application(printSystemProperties) ] -> file:/opt/jdown2/build.json:
{"JDownloaderServerOptionsRevision":5556,"buildTimestamp":1670606425112,"UpdateClientV2Revision":1038,"JDownloaderUpdaterRevision":5660,"AppWorkUtilsRevision":3891,"JDBrowserRevision":47172,"JDClosedRevision":884,"MyJDownloaderClientRevision":46032,"buildDate":"Fri Dec 09 18:20:25 CET 2022","JDownloaderRevision":47198}
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.jdownloader.update.launcher.SecondLevelLauncher(init) ] -> Args: [-norestart]
1|org.jdownloader.updatev2.restart.LinuxRestarter.log 12/17/22, 4:52:59 PM - INFO [ org.jdownloader.updatev2.restart.Restarter(<init>) ] -> Create Restarter
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.jdownloader.update.launcher.SecondLevelLauncher(init) ] -> Restart Controller init done in 19
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.jdownloader.update.launcher.SecondLevelLauncher(init) ] -> Parse Arguments
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.jdownloader.update.launcher.SecondLevelLauncher(init) ] -> Parameter Parse done in 1
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.jdownloader.update.launcher.SecondLevelLauncher(init) ] -> Single Instance Controller
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.jdownloader.update.launcher.SecondLevelLauncher(init) ] -> existing jD instance found!
1|org.jdownloader.update.launcher.SecondLevelLauncher.log 12/17/22, 4:52:59 PM - INFO [ org.jdownloader.update.launcher.SecondLevelLauncher(init) ] -> Send parameters to existing jD instance and exit: [-norestart]

THREAD: 10
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [1/8|Priority: 10000]ShutdownController: start item->org.appwork.shutdown.ShutdownRunableEvent Priority: 10000
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [1/8|Priority: 10000]ShutdownController: item ended after->3
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:1/8]
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [2/8|Priority: 10000]ShutdownController: start item->flushing logs to disk
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [2/8|Priority: 10000]ShutdownController: item ended after->27
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:2/8]
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [3/8|Priority: 0]ShutdownController: start item->ShutdownEvent: Save JSonStorages

THREAD: 22
22|Log.L.log 12/17/22, 4:52:59 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> Start Saving Storage
22|Log.L.log 12/17/22, 4:52:59 PM - FINER [ org.appwork.loggingv3.LogV3(finer) ] -> ENDED Saving Storage
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [3/8|Priority: 0]ShutdownController: item ended after->3
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:3/8]
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [4/8|Priority: 0]ShutdownController: start item->ShutdownEvent: SaveAllStorageHandler
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [4/8|Priority: 0]ShutdownController: item ended after->1
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:4/8]
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [5/8|Priority: 0]ShutdownController: start item->ShutdownEvent: ProcessDelayedWrites num=0
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [5/8|Priority: 0]ShutdownController: item ended after->3
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:5/8]
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [6/8|Priority: -2147483648]ShutdownController: start item->org.jdownloader.updatev2.RestartController$1 Priority: -2147483648
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [6/8|Priority: -2147483648]ShutdownController: item ended after->2
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:6/8]
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [7/8|Priority: -2147483648]ShutdownController: start item->ShutdownEventWrapper Thread[Logging-Cleaner,5,main] - java.util.logging.LogManager$Cleaner Priority: -2147483648
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [7/8|Priority: -2147483648]ShutdownController: item ended after->7
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:7/8]
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [8/8|Priority: -2147483648]ShutdownController: start item->ShutdownEventWrapper Thread[Logging-Cleaner,5,main] - java.util.logging.LogManager$Cleaner Priority: -2147483648
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [8/8|Priority: -2147483648]ShutdownController: item ended after->6
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> [Done:8/8]
10|org.appwork.shutdown.ShutdownController.log 12/17/22, 4:52:59 PM - INFO [ org.appwork.shutdown.ShutdownController(log) ] -> Shutdown Hooks Finished

**Comment by Diegoloex** [comment]
the magic not found for mi... @ @
