### ISSUE TITLE
Tvheadend stops at Adding Repo

### ISSUE THREAD

**Issue by nibotg** [StevenSeifried/proxmox-scripts#13]
Many thanks for providing these scripts and sorry to trouble you.
I copied your link to install TVHeadend but unfortunately it only gets as far as "Adding Tvheadend Repo" and then just seems to stop: 
 `
✔  Updating LXC Template List... 
✔  Downloading LXC Template... 
✔  Creating LXC Container... 
✔  Starting LXC Container... 
✔  Setting up Container OS... 
✔  Updating Container OS... 
✔  Installing Prerequisites... 
✔  Adding Tvheadend Repo...`

Any suggestion gratefully received please,
Thanks
Grahame

**Comment by nibotg** [comment]
Apologies, I've retried this and it now doesn't get any further than:

✔  Updating LXC Template List... 
✔  Downloading LXC Template... 
✔  Creating LXC Container... 
✔  Starting LXC Container... 
✔  Setting up Container OS... 
✔  Updating Container OS... 
✔  Installing Prerequisites... 
✔  Installing Tvheadend...

Thanks

**Comment by StevenSeifried** [comment]
This is the problem:
![grafik](https://user-images.githubusercontent.com/39765956/226708303-d0168007-09ad-44ad-9670-f67e6ff50738.png)
That is why the script stops

Unfortunately, I don't know how to fix this. I'll remove the tvheadend scripts.

**Comment by nibotg** [comment]
Ah, ok, that's a shame. Thanks for looking into it.
