### ISSUE TITLE
Not an issue, just want some info.

### ISSUE THREAD

**Issue by Cueball666uk** [StevenSeifried/proxmox-scripts#17]
I'm interested in installing a Jdownloader2 LXC, but would like some info on possibly installing with 1 or maybe 2gb storage instead of the 32gb as I'll be linking to my Synology nas via NFC. Thank you for any help.

**Comment by StevenSeifried** [comment]
Just replace 32GB with the value you prefer in [line 133](https://github.com/StevenSeifried/proxmox-scripts/blob/main/ct/jdownloader2_container.sh#L133)
